name: Build and Deploy to PyPI

on: push

permissions:
  id-token: write
  contents: read

jobs:

  build-and-publish:
    name: Build and deploy to PyPI
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"

    - name: Poetry setup tools
      run: poetry add setuptools==60.0.0

    - name: Install Dependencies
      run: poetry install

    - name: Build Package
      run: poetry build

    - name: Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_password }}
        skip_existing: true
